name: Main

on:
  push:
    tags:
    - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
      packages: write
      discussions: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.20'

    - name: Build
      run: ./build.sh ${{ github.ref_name }}

    - name: Upload asset
      uses: softprops/action-gh-release@v1
      with:
        files: caddy-arm64

    - name: Log in to registry
      run: |
        docker login \
          -u ${{ github.actor }} \
          -p ${{ secrets.GITHUB_TOKEN }} \
          ${{ env.REGISTRY }}

    - name: Set image metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
